Test Results100% ||Average Loss: 0.5151, Average Dice Score: 0.7595[Finetuning] Epoch: 1 Avg Loss: 0.3156[Validation] Avg Loss: 0.3092, Avg Dice Score: 0.8896100%[Finetuning] Epoch: 2 Avg Loss: 0.3055[Validation] Avg Loss: 0.3059, Avg Dice Score: 0.8947 100% |[Finetuning] Epoch: 3 Avg Loss: 0.3021[Validation] Avg Loss: 0.3055, Avg Dice Score: 0.8948 100% ||[Finetuning] Epoch: 4 Avg Loss: 0.2987[Validation] Avg Loss: 0.3049, Avg Dice Score: 0.8928100%[Finetuning] Epoch: 5 Avg Loss: 0.2958[Validation] Avg Loss: 0.3054, Avg Dice Score: 0.8960 100%||[Finetuning] Epoch: 6 Avg Loss: 0.2940[Validation] Avg Loss: 0.3034, Avg Dice Score: 0.8949 100% |[Finetuning] Epoch: 7 Avg Loss: 0.2945[Validation] Avg Loss: 0.3011, Avg Dice Score: 0.8991 100% ||[Finetuning] Epoch: 8 Avg Loss: 0.2917[Validation] Avg Loss: 0.3112, Avg Dice Score: 0.8832100%[Finetuning] Epoch: 9 Avg Loss: 0.2918[Validation] Avg Loss: 0.3033, Avg Dice Score: 0.8937 100%|| [Finetuning] Epoch: 10 Avg Loss: 0.2890[Validation] Avg Loss: 0.3043, Avg Dice Score: 0.8920143/143 [00:14<00:00, 10.07it/s]143/143 [00:14<00:00, 9.91it/s]143/143 [00:14<00:00, 10.03it/s]143/143 [00:14<00:00, 9.86it/s]143/143 [00:14<00:00, 10.01it/s]143/143 [00:14<00:00, 9.99it/s]143/143 [00:14<00:00, 9.92it/s]143/143 [00:14<00:00, 10.04it/s]143/143 [00:14<00:00, 9.88it/s]143/143 [00:14<00:00, 9.97it/s]/home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to 'self.log()' but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6699, Average Dice Score: 0.6883