Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100%||[Finetuning] Epoch: 1 Avg Loss: 0.3145[Validation] Avg Loss: 0.3109, Avg Dice Score: 0.8955 100%||[Finetuning] Epoch: 2 Avg Loss: 0.3070[Validation] Avg Loss: 0.3099, Avg Dice Score: 0.8958 100% ||[Finetuning] Epoch: 3 Avg Loss: 0.3017[Validation] Avg Loss: 0.3103, Avg Dice Score: 0.8983100%[Finetuning] Epoch: 4 Avg Loss: 0.2999[Validation] Avg Loss: 0.3112, Avg Dice Score: 0.8961 100%||[Finetuning] Epoch: 5 Avg Loss: 0.2972[Validation] Avg Loss: 0.3091, Avg Dice Score: 0.8996 100% |[Finetuning] Epoch: 6 Avg Loss: 0.2942[Validation] Avg Loss: 0.3093, Avg Dice Score: 0.8945 100% ||[Finetuning] Epoch: 7 Avg Loss: 0.2934[Validation] Avg Loss: 0.3060, Avg Dice Score: 0.9030100%[Finetuning] Epoch: 8 Avg Loss: 0.2895[Validation] Avg Loss: 0.3069, Avg Dice Score: 0.9007 100%||[Finetuning] Epoch: 9 Avg Loss: 0.2882[Validation] Avg Loss: 0.3169, Avg Dice Score: 0.8808 100%||[Finetuning] Epoch: 10 Avg Loss: 0.2898143/143 [00:13<00:00, 10.37it/s]143/143 [00:14<00:00, 10.17it/s]143/143 [00:14<00:00, 10.12it/s]143/143 [00:14<00:00, 10.21it/s]143/143 [00:14<00:00, 10.04it/s]143/143 [00:13<00:00, 10.30it/s]143/143 [00:13<00:00, 10.30it/s]143/143 [00:14<00:00, 10.21it/s]143/143 [00:14<00:00, 10.18it/s]143/143 [00:13<00:00, 10.24it/s][Validation] Avg Loss: 0.3107, Avg Dice Score: 0.8916 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6011, Average Dice Score: 0.7223