Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100%||[Finetuning] Epoch: 1 Avg Loss: 0.3163[Validation] Avg Loss: 0.3039, Avg Dice Score: 0.8981100%[Finetuning] Epoch: 2 Avg Loss: 0.3066[Validation] Avg Loss: 0.3018, Avg Dice Score: 0.9022 100% |[Finetuning] Epoch: 3 Avg Loss: 0.3026[Validation] Avg Loss: 0.3032, Avg Dice Score: 0.9026 100% ||[Finetuning] Epoch: 4 Avg Loss: 0.2991[Validation] Avg Loss: 0.2952, Avg Dice Score: 0.9018100%[Finetuning] Epoch: 5 Avg Loss: 0.2959[Validation] Avg Loss: 0.3009, Avg Dice Score: 0.8905 100%||[Finetuning] Epoch: 6 Avg Loss: 0.2952[Validation] Avg Loss: 0.2996, Avg Dice Score: 0.8920 100% |[Finetuning] Epoch: 7 Avg Loss: 0.2928[Validation] Avg Loss: 0.2969, Avg Dice Score: 0.8955 100% ||[Finetuning] Epoch: 8 Avg Loss: 0.2929[Validation] Avg Loss: 0.2995, Avg Dice Score: 0.8921100%[Finetuning] Epoch: 9 Avg Loss: 0.2937[Validation] Avg Loss: 0.3007, Avg Dice Score: 0.8883 100%|| [Finetuning] Epoch: 10 Avg Loss: 0.2905[Validation] Avg Loss: 0.2961, Avg Dice Score: 0.8960143/143 [00:14<00:00, 10.03it/s]143/143 [00:13<00:00, 10.23it/s]143/143 [00:13<00:00, 10.34it/s]143/143 [00:13<00:00, 10.28it/s]143/143 [00:13<00:00, 10.45it/s]143/143 [00:14<00:00, 10.15it/s]143/143 [00:13<00:00, 10.25it/s]143/143 [00:14<00:00, 10.21it/s]143/143 [00:13<00:00, 10.35it/s]143/143 [00:13 00:00, 10.24it/s]/home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to 'self.log()' but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6015, Average Dice Score: 0.7219