Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100%||[Finetuning] Epoch: 1 Avg Loss: 0.3152[Validation] Avg Loss: 0.3156, Avg Dice Score: 0.8945100%[Finetuning] Epoch: 2 Avg Loss: 0.3058[Validation] Avg Loss: 0.3164, Avg Dice Score: 0.8933 100% |[Finetuning] Epoch: 3 Avg Loss: 0.2996[Validation] Avg Loss: 0.3119, Avg Dice Score: 0.8983 100% ||[Finetuning] Epoch: 4 Avg Loss: 0.2971[Validation] Avg Loss: 0.3201, Avg Dice Score: 0.8813100%[Finetuning] Epoch: 5 Avg Loss: 0.2954[Validation] Avg Loss: 0.3187, Avg Dice Score: 0.8851 100%||[Finetuning] Epoch: 6 Avg Loss: 0.2950[Validation] Avg Loss: 0.3169, Avg Dice Score: 0.8899 100% |[Finetuning] Epoch: 7 Avg Loss: 0.2933[Validation] Avg Loss: 0.3171, Avg Dice Score: 0.8884 100% ||[Finetuning] Epoch: 8 Avg Loss: 0.2912[Validation] Avg Loss: 0.3134, Avg Dice Score: 0.8934100%[Finetuning] Epoch: 9 Avg Loss: 0.2892[Validation] Avg Loss: 0.3157, Avg Dice Score: 0.8875 100%||[Finetuning] Epoch: 10 Avg Loss: 0.2891143/143 [00:14<00:00,9.94it/s]143/143 [00:14<00:00, 10.08it/s]143/143 [00:14<00:00, 10.03it/s]143/143 [00:14<00:00, 10.08it/s]143/143 [00:13<00:00, 10.24it/s]143/143 [00:13<00:00, 10.23it/s]143/143 [00:14<00:00, 10.16it/s]143/143 [00:14<00:00, 10.20it/s]143/143 [00:13<00:00, 10.27it/s]143/143 [00:13 00:00, 10.22it/s]er'[Validation] Avg Loss: 0.3128, Avg Dice Score: 0.8944 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to 'self.log()` but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Train Test Results - Average Loss: 0.6024, Average Dice Score: 0.7214