Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100%||[Finetuning] Epoch: 1 Avg Loss: 0.3179[Validation] Avg Loss: 0.2883, Avg Dice Score: 0.8915100%[Finetuning] Epoch: 2 Avg Loss: 0.3088[Validation] Avg Loss: 0.2937, Avg Dice Score: 0.8812 100% |[Finetuning] Epoch: 3 Avg Loss: 0.3046[Validation] Avg Loss: 0.2862, Avg Dice Score: 0.8931 100% ||[Finetuning] Epoch: 4 Avg Loss: 0.3018[Validation] Avg Loss: 0.2883, Avg Dice Score: 0.8905100%[Finetuning] Epoch: 5 Avg Loss: 0.2986[Validation] Avg Loss: 0.2820, Avg Dice Score: 0.8992 100%||[Finetuning] Epoch: 6 Avg Loss: 0.2947[Validation] Avg Loss: 0.2833, Avg Dice Score: 0.8983 100% |[Finetuning] Epoch: 7 Avg Loss: 0.2929[Validation] Avg Loss: 0.2914, Avg Dice Score: 0.8870 100% ||[Finetuning] Epoch: 8 Avg Loss: 0.2923[Validation] Avg Loss: 0.2874, Avg Dice Score: 0.8912100%[Finetuning] Epoch: 9 Avg Loss: 0.2928[Validation] Avg Loss: 0.2820, Avg Dice Score: 0.9003 100%|| [Finetuning] Epoch: 10 Avg Loss: 0.2925[Validation] Avg Loss: 0.2922, Avg Dice Score: 0.8846143/143 [00:13<00:00, 10.82it/s]143/143 [00:13<00:00, 10.59it/s]143/143 [00:13<00:00, 10.80it/s]143/143 [00:13<00:00, 10.84it/s]143/143 [00:13<00:00, 10.46it/s]143/143 [00:13<00:00, 10.78it/s]143/143 [00:13<00:00, 10.66it/s]143/143 [00:13<00:00, 10.59it/s]143/143 [00:13<00:00, 10.71it/s]143/143 [00:13 00:00, 10.75it/s]/home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Train Test Results - Average Loss: 0.6364, Average Dice Score: 0.7058er'